### ISSUE TITLE
is it on youtube?

### ISSUE THREAD

**Issue by nikhildr22** [flatplanet/Intro-To-TKinter-Youtube-Course#3]
if the course is on youtube, please add a link to the youtube course in a README file,
thanks

**Comment by dineshssdn-867** [comment]
Yes it is checkout the link: https://youtu.be/YXPyB4XeYLA

**Comment by nikhildr22** [comment]
Thank you @dineshssdn-867 , I found this repo, but couldn't find its source. thanks again
